import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
// import Navbar from '../components/Navbar'
import Navbarsign from '../../components/Navbarsign'
import Cards from '../../components/Card'
import {useState} from 'react'
import axios from 'axios' 

export default function HomeLogin() {
  const [display, setDisplay] = useState(styles.hide)
  const [subList, setSubList] = useState([])
  const [subItem, setSubItem] = useState([])

  const changeDisplay = async (e, kategori) => {
      e.preventDefault()
      if (display == styles.hide) {
        setDisplay(styles.show)

        try {
           const data = await axios.get(`http://localhost:3000/api/sub-list`)
           setSubList(data.data)
           console.log(subList)

        } catch (err) {
          console.log(err)
        }
      }
      
      else {
        setDisplay(styles.hide)
      }
  }

  const getItemList = async (e, subKategori) => {
    e.preventDefault(
      
    )
    console.log(`Klik sub ${subKategori}`)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Navbar></Navbar> */}
      <Navbarsign> </Navbarsign>
      <header className={styles.header}>
        <h1>Selamat Datang di Rumahrumus</h1>
        <div className={styles.fitur}>
          <div>
              <img src='./cari_rumus.png'/>
              <p>Dengan fitur <span>Cari Rumus</span> kamu bisa mencari rumus yang kamu perlukan</p>
          </div>
          <div>
              <img src='./rumus_saya.png'/>
              <p>Dengan fitur <span>Rumus Saya</span> kamu bisa menyimpan rumus yang kamu cari</p>
          </div>
          <div>
              <img src='./buat_rumus.png'/>
              <p>Dengan fitur <span>Buat Rumus</span> kamu bisa membuat rumus cepat versimu</p>
          </div>
        </div>
      </header>

      <main className={styles.main}>
          <div className={styles.search}>
             <h1>Cari Rumus mu Disini !</h1>
             <input type = 'text' id='searching' placeholder='masukan keyword disini..'></input>
             <button>Cari</button>
          
             <div className={styles.kategori}>
                <a href onClick={(event) => changeDisplay(event, "Matematika")}>Matematika</a>
                <a href onClick={(event) => changeDisplay(event, "Fisika")}>Fisika</a>
                <a href onClick={(event) => changeDisplay(event, "Kimia")}>Kimia</a>
                <a href onClick={(event) => changeDisplay(event, "Ekonomi")}>Ekonomi</a>
          </div>
          </div>

          <div className={display}>
            <div className={styles.subKategori}>

            {subList.map((item) => <p onClick={(event) => getItemList(event, 'matematika')}><a href=".">{item}</a></p>)}
          

             {/* <p><a href="">Bangun Datar</a></p> */}
             {/* <p><a href="">Bangun Ruang</a></p>
             <p><a href="">Bilangan Bulat</a></p>
             <p><a href="">Bilangan Pecahan</a></p>
             <p><a href="">Bilangan Berpangkat</a></p> */}
            </div>
        </div>

          <h2>Title</h2>

          <div className={styles.container2}>
            <Cards></Cards>
          </div>

      </main>
      
      <footer className={styles.footer}>
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}
      </footer>
    </div>
  )
}
