import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Navbarsign from '../components/Navbarsign'
import Cards from '../components/Card'
import {useState} from 'react'
import axios from 'axios' 

export default function Home() {
  const [display, setDisplay] = useState(styles.hide)
  const [currId, setCurrId] = useState(0)
  const [subList, setSubList] = useState([])
  const [rumus, setRumus] = useState([])

  const handleCategory = async (e, id) => {
      e.preventDefault()
      if (display == styles.hide || (display == styles.show && id != currId)) {
        setDisplay(styles.show)
        setCurrId(id)

        try {
           const result = await axios.get(`http://localhost:8000/sct/subByCategId/${id}`)
          //  setSubList(data.data)
           setSubList(result.data.data)

        } catch (err) {
          console.log(err)
        }
      }
      
      else {
        setDisplay(styles.hide)
        setCurrId(0)
      }
  }

  const handleRumus = async (e, id) => {
    e.preventDefault()

    try {
      const result = await axios.get(`http://localhost:8000/rumus/subcateg/${id}`)
      //  setSubList(data.data)
       setRumus(result.data.data)
      
    } catch (error) {
       console.log(error)
    }
    
    console.log(`Klik sub ${id}`)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar></Navbar>
      {/* <Navbarsign> </Navbarsign> */}
      <header className={styles.header}>
        <h1>Selamat Datang di Rumahrumus</h1>
        <div className={styles.fitur}>
          <div>
              <img src='./cari_rumus.png'/>
              <p>Dengan fitur <span>Cari Rumus</span> kamu bisa mencari rumus yang kamu perlukan</p>
          </div>
          <div>
              <img src='./rumus_saya.png'/>
              <p>Dengan fitur <span>Rumus Saya</span> kamu bisa menyimpan rumus yang kamu cari</p>
          </div>
          <div>
              <img src='./buat_rumus.png'/>
              <p>Dengan fitur <span>Buat Rumus</span> kamu bisa membuat rumus cepat versimu</p>
          </div>
        </div>
      </header>

      <main className={styles.main}>
          <div className={styles.search}>
             <h1>Cari Rumus mu Disini !</h1>
             <input type = 'text' id='searching' placeholder='masukan keyword disini..'></input>
             <button>Cari</button>
          
             <div className={styles.kategori}>
                <a href onClick={(event) => handleCategory(event, 1)}>Matematika</a>
                <a href onClick={(event) => handleCategory(event, 2)}>Fisika</a>
                <a href onClick={(event) => handleCategory(event, 3)}>Kimia</a>
                <a href onClick={(event) => handleCategory(event, 4)}>Ekonomi</a>
          </div>
          </div>

          <div className={display}>
            <div className={styles.subKategori}>
              {subList.map((item) => <p onClick={(event) => handleRumus(event, item.id)} key={item.id} list={item.name}>{item.name}</p>)}
            </div>
        </div>

         

          <div className={styles.container2}>
            {/* <Cards></Cards> */}
            {rumus.map((item) => <Cards key={item.id} data={item}></Cards>)}
          </div>

      </main>
      
      <footer className={styles.footer}>
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}
      </footer>
    </div>
  )
}
