import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Cards from '../components/Card'
import Footer from '../components/Footer'

import {useState, useEffect} from 'react'
import axios from 'axios' 



export default function Home() {
  const [display, setDisplay] = useState(styles.hide)
  const [hover, setHover] = useState([])
  const [getRum, setgetRum] = useState([])
  const [subList, setSubList] = useState([])
  const [rumus, setRumus] = useState([])

  useEffect(() => {
    fetch(`${process.env.NEXT_PUBLIC_API_URL}/rumus/all`)
      .then((res) => res.json())
      .then((data) => {
        setRumus(data.data)
      })
        // handleList()
  }, [])

  const handleRumus = async (e) => {
    // selectElement = document.querySelector('#select1')
    // output = selectElement.option[selectElement.selectedIndex].value;
    e.preventDefault()

    try {
      const id = document.getElementById('sub').value
      const result = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/rumus/subcateg/${id}`)
      //  setSubList(data.data)
       setRumus(result.data.data)
       
      
    } catch (error) {
       console.log(error)
    }
    
    // console.log(`Klik sub ${id}`)
  }


  const handleList = async (e,id) => {

    try {
      e.preventDefault()

      if (id === 0) {
                
              const respone = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/rumus/all`)
              setRumus(respone.data.data)
              console.log('Rumus', rumus)


      } else {

            const id = document.getElementById('ct').value

            const respone = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/sct/subByCategId/${id}`)
            setSubList(respone.data.data)

            console.log('Rumus', rumus)
            
            const result = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/rumus/categ/${id}`)
            //  setSubList(data.data)
            setRumus(result.data.data)
       
    
      // const rum = await axios.get(`http://localhost:8000/rumus/subcateg/${id}`)
      // //     //  setSubList(data.data)
      // setRumus(rum.data.data)
  }
    } catch (error) {
       console.log(error)
    }

  }


  const handleSearching = async (e, key) => {
    try {
      e.preventDefault()
      const response = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/rumus/keyword?key=${key}`)
      console.log('Key: ', key, ' Res: ', response.data.data)
      // setRumus(response.data.data)

      if (response.data.status == 404){
        setRumus([])

      } else {
        setRumus(response.data.data)
      }

      // console.log(response)
    }

      catch(err) {
      console.log(err)
    }
  }



 


  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>RumahRumusApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/rumahrumus_logo.png" className={styles.logo} />
      </Head>

      <Navbar></Navbar>
      {/* <Navbarsign> </Navbarsign> */}
      <header className={styles.header}>
        <h1>Selamat Datang di RumahRumus</h1>
        <div className={styles.fitur}>
          <div>
              <img src='./cari_rumus.png'/>
              <p>Dengan fitur <span>Cari Rumus</span> kamu bisa mencari rumus yang kamu perlukan</p>
          </div>
          <div>
              <img src='./rumus_saya.png'/>
              <p>Dengan fitur <span>Rumus Saya</span> kamu bisa menyimpan rumus yang kamu cari</p>
          </div>
          <div className={styles.buatrumus}>
              <img src='./buat_rumus.png'/>
              <p>Dengan fitur <span>Buat Rumus</span> kamu bisa membuat rumus cepat versimu</p>
          </div>
        </div>
      </header>

      <main className={styles.main}>
        <h1>Cari Rumus Kamu Disini Yuk!</h1>

        <div className={styles.mainsearch}>
          {/* <div className={styles.dropdown}> */}
            <select id='ct' onChange={(event)=> handleList(event)}>
              <option value={0}>Pilih Kategori</option>
              <option value={1}>Matematika</option> 
              <option value={2} >Fisika</option> 
              <option value={3} >Kimia</option> 
              <option value={4} >Ekonomi</option>
            </select>

            <select id='sub' onChange={(event)=> handleRumus(event)}> 
              <option value={0}>Pilih Sub Kategori</option>
              {subList.map((item) => <option  value={item.id} key={item.id} >{item.name}</option>)}
            </select>
           
      {/* <div className={styles.search}> */}
            <input  type = 'text' id='key' placeholder='masukan keyword ...'></input>
            <button onSubmit={(event) => handleSearching(event, document.getElementById('key').value)} onClick={(event) => handleSearching(event, document.getElementById('key').value)}>Cari</button>
            {/* {rumus.length == 0?: <div className={styles.searchnotfound}><p>Hasil pencarianmu...</p><img src='./rumusnotfound.png'/></div>} */}
          {/* </div> */}
          {/* </div> */}
    
        </div>

        <div className={styles.container2}>
          {/* {getRum.length == 1? <div className={styles.searchnotfound}><p>Hasil pencarianmu...</p><img src='./rumusnotfound.png'/></div>:getRum.map((item) => <Cards key={item.id} data={item}></Cards>)} */}
          {rumus.length == 0? <div className={styles.searchnotfound}><p>Hasil pencarianmu...</p><img src='./rumusnotfound.png'/></div>:rumus.map((item) => <Cards key={item.id} data={item}></Cards>)}
        </div> 
      </main>
      
      {/* <footer className={styles.footer}>
      </footer> */}
     <Footer></Footer>
    </div>
    </>
  )
}

